language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.0
   - DB=MYSQL CORE_RELEASE=3.1
   - DB=MYSQL CORE_RELEASE=3.2
   - DB=SQLITE CORE_RELEASE=3.0
   - DB=SQLITE CORE_RELEASE=3.1
   - DB=SQLITE CORE_RELEASE=3.2

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=master
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=master
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=master
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=master
    - php: 7.0
      env: DB=SQLITE CORE_RELEASE=master
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=master

before_script:
  - phpenv rehash
  - composer self-update
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit abc-silverstripe-taggable/tests/
